name: valetparking_user
description: "A valet parking user."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

  #-------------------- PACKAGES --------------------#

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Utility Package
  floating_snackbar: ^1.0.5
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.1
  intl: ^0.19.0

  # Local Database
  shared_preferences: ^2.3.2

  # Icons
  iconsax_flutter: ^1.0.0

  # Animation
  lottie: ^3.1.2

  # Images
  image_picker: ^1.1.2

  # Loading Shimmer
  shimmer: ^3.0.0

  # Animated Loading
  flutter_spinkit: ^5.2.1

  # State Management
  flutter_bloc: ^8.1.6

  # Make Banner
  carousel_slider: ^5.0.0

  # To Call Backend
  dio: ^5.6.0

  # Image Cach
  cached_network_image: ^3.4.1

  # Responsive Ui
  flutter_screenutil: ^5.9.3

  # Make Animation When Navigate
  page_transition: ^2.1.0

  # SVG Pictures
  flutter_svg: ^2.0.10+1

  # Custom Field On OTP
  pinput: ^5.0.0

  # Dotted Container
  dotted_border: ^2.1.0

  # Get Location
  geolocator: ^13.0.1
#  location: ^6.0.2
#  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  maps_launcher: ^2.2.1
#  flutter_polyline_points: ^2.1.0
#  google_places_flutter: ^2.0.9

  permission_handler: ^11.3.1
  path_provider: ^2.1.4

  # Calender
  table_calendar: ^3.0.9

  # Timer
  percent_indicator: ^4.2.2
  flutter_countdown_timer: ^4.1.0


  # Translation
  flutter_localizations:
    sdk: flutter

  #-------------------- PACKAGES End --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  #-------------------- LOCAL ASSETS --------------------#

  assets:
    - lang/
    - assets/images/jpgs/
    - assets/images/pngs/
    - assets/images/svgs/
    - assets/images/lotties/

  #-------------------- LOCAL FONTS --------------------#

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/en/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/en/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/en/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/en/Urbanist-Bold.ttf
          weight: 800
    - family: Cairo
      fonts:
        - asset: assets/fonts/ar/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/ar/Cairo-Light.ttf
          weight: 500
        - asset: assets/fonts/ar/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ar/Cairo-Bold.ttf
          weight: 800
